# Generated by Django 4.1.2 on 2023-01-19 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup_info',
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='signup_info',
            name='Full_Name',
        ),
        migrations.RemoveField(
            model_name='signup_info',
            name='Location',
        ),
    ]
